configfile: "config.yaml"

ref_genome,=glob_wildcards("../resources/ref_genome/{reference_genome}.fasta")
sample,=glob_wildcards("../resources/samples/{sample_id}_R1_001.fastq")

shell("bwa index ../resources/ref_genome/{ref_genome}.fasta")

rule all:
 input:
  expand("../results/varscan_output/varscan_readcounts.txt")

rule bwa_map:
 input:
  r1="../resources/samples/{sample}_R1_001.fastq",
  r2="../resources/samples/{sample}_R2_001.fastq"
 output: 
  "../results/mapped_reads/{sample}.bam"
 shell:
  "bwa mem ../resources/{ref}.fasta {input.r1} {input.r2} | samtools view -Sb -o {output}"

rule samtools_sort:
 input: 
  "../results/mapped_reads/{sample}.bam"
 output: 
  "../results/sorted_reads/{sample}.bam"
 shell:
  "samtools sort {input} > {output}"

rule samtools_index:
 input:
  "../results/sorted_reads/{sample}.bam"
 output:
  "../results/sorted_reads/{sample}.bam.bai"
 shell:
  "samtools index {input}"

rule samtools_mpileup:
 input:
  bam=expand("../results/sorted_reads/{sample}.bam",sample=sample),
  bai=expand("../results/sorted_reads/{sample}.bam.bai",sample=sample)
 output:
  "../results/mpileup/combined.mpileup"
 params:
  max_read_depth=lambda wc: config['max_read_depth'],
  qscore=lambda wc: config['qscore']
 shell:
  "samtools mpileup -A -d {params.max_read_depth} -Q {params.qscore} -f resources/{ref}.fasta {input.bam} > {output}"

rule varscan:
 input:
  "../results/mpileup/combined.mpileup"
 output:
  "../results/varscan_output/varscan_readcounts.txt"
 params:
  var_file=lambda wc: config['var_file'],
  min_base_qual=lambda wc: config['min_base_qual']
 shell:
  "varscan readcounts {input} --variants-file ../resources/{params.var_file} --min-base-qual {params.min_base_qual} --output-file {output}"

